[package]
name = "hole_punch"
version = "0.1.0"
authors = ["chili-b <dexter.gaonshatford@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
laminar = "0.5.0"
crossbeam-channel = "0.5.1"
anyhow = "1.0.40"
